spring:
  application:
    name: Ludotheque

  #Connection to DB
  datasource:
    url: jdbc:sqlserver://localhost;databasename=${DB_NAME};integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  #Options to DB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create